### ISSUE TITLE
Again can not download daily build ISO

### ISSUE THREAD

**Issue by zchee** [NextBSD-classic/NextBSD-classic#34]
`404 Not Found` on `disc1-201601030303.iso` later all ISO.
e.g. http://build.nextbsd.org/data/disc1-201601130302.iso

The same cause as the https://github.com/NextBSD/NextBSD/issues/32 problem?

If you have a time, Could you advise me of self iso building work?
or, How to launch auto build server.

If the build server is not enough, I might be able to cooperate.

**Comment by jordanhubbard** [comment]
Sorry, the build server is “supported” as a free time thing on my part and I frequently forget to check to see if it’s run out of space.  Also, my build script is extremely stupid and doesn’t prune older images or otherwise try to be more than a 20 line shell script I banged together one evening. :)

If you have a little time to donate, perhaps you could write me a script which does release builds of NextBSD (and updates an index.html file to point to them) and also garbage-collects builds after a certain number of days?

It would be very easy to run a find and nuke any .iso files older than, say, 7 days but that would also leave the index.html file pointing at builds that had been deleted, so we need to do the HTML generation as part of the build / garbage collection process and I suck at HTML.. :)
- Jordan

**Comment by jordanhubbard** [comment]
P.S. The old builds are cleaned out and a new build is running now - it should be up shortly!

**Comment by zchee** [comment]
@jordanhubbard Thanks reply!

I want to write a script :) 
but, Where can I find the build server code and old scripts?
Since I have not used the FreeBSD, I want to know how these are built.

**Comment by jordanhubbard** [comment]
> On Jan 14, 2016, at 12:12 AM, Koichi Shiraishi notifications@github.com wrote:
> 
> I want to write a script :) 
> but, Where can I find the build server code and old scripts?
> Since I have not used the FreeBSD, I want to know how these are built.
> 
> This is it - this is all there is. :)

#!/bin/sh
D=`date -u '+%Y%m%d%H%M'`
N=/usr/local/www/nginx/data

befunge()
{
    sed -e "s;<!COMMENT>;ISO image from <a href="disc1-$1.iso">$1</a> GMT<p></p><!COMMENT>;" < $N/index.html > $N/index.html.new && mv $N/index.html.new $N/index.html
}

cd /usr/home/freebsd/NextBSD
git pull --rebase=true
if make buildworld buildkernel NO_CLEAN=yes > make.out 2>&1; then
    echo "Buildworld buildkernel successful at $D GMT" >> ../build.status
    cd release
    if make cdrom > release.out 2>&1; then
        mv disc1.iso $N/disc1-$D.iso
        befunge $D
    else
        tail -50 release.out | mail -s "NextBSD release failure at $D" jkh@ixsystems.com
    fi
else
    tail -50 make.out| mail -s "NextBSD build failure at $D" jkh@ixsystems.com
fi

As I said, it’s extremely simple (simplistic would be a better word).
- Jordan

**Comment by zchee** [comment]
@jordanhubbard Thanks :)
and, I was able to download latest iso.

I launched FreeBSD OS in AWS, and testing this script.

I'll rewrite script later.

**Comment by zchee** [comment]
@jordanhubbard and, that Issue has been resolved.
I will close for now.
